export const themeColor = {
  appBackgroundColor: "#01081F",
  textColor: "#fff",
  textHighlightColor: "#f0f0f0",
  buttonPrimaryBackgroundColor: "#3671E9",
  backgroundHighlightColor: "#f7a641",
  buttonPrimaryTextColor: "#fff",
  buttonOutlineBackgroundColor: "#3671E9",
  buttonOutlineTextColor: "#fff",
  disabledButtonBackgroundColor: "#e5dee3",
  disabledButtonTextColor: "#aba1a9",
  neutralColor: "#B3B3B3",
  checkedColor: "#55FE66",
  errorColor: "#FF0000",
  modalBottomBackgroundColor: "#121212",
  phraseBorderColor: "#388BFF",
  phraseCardBackgroundColor: "#333333",
  disabledPhrasesBackgroundColor: "#34394c",
  cardBackgroundColor: "#001431",
};
